#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const projectRoot = path.resolve(__dirname, "..");
const envPath = path.join(projectRoot, ".env.local");

function randomHex(bytes = 32) {
  return crypto.randomBytes(bytes).toString("hex");
}

const jwtSecret = randomHex(32);
const encryptionSalt = randomHex(24);

const defaultDbUrl =
  process.env.LOCAL_DB_URL ||
  "postgresql://postgres:postgres@localhost:5432/zet_asociatie";

const content = `# Generated by scripts/generate-env.js - safe to edit
# Local PostgreSQL and auth

LOCAL_DB_URL=${defaultDbUrl}
JWT_SECRET=${jwtSecret}
ENCRYPTION_SALT=${encryptionSalt}
`;

fs.writeFileSync(envPath, content, "utf8");
console.log("Wrote", envPath);
console.log("");
console.log("Next steps:");
console.log("  1. Create the database (if needed): createdb zet_asociatie");
console.log("  2. If you use a different Postgres user/password, edit LOCAL_DB_URL in .env.local");
console.log("  3. Run migrations: node scripts/migrate.js");
console.log("  4. Start the app: npm run dev");
console.log("  5. Create first user: POST /api/auth/register with { \"email\", \"password\", \"full_name\", \"role\" }");
console.log("");
